org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
org.gradle.java.home=C:/Program Files/Android/openjdk/jdk-21.0.8
kotlin.incremental=false
org.gradle.vfs.watch=false
org.gradle.daemon=false
