// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ISCdILC8Hpb6FT9qq4mNS_1nZ3Ei-BE',
    appId: '1:726749633874:web:d8174d6eeb8523f122ae8b',
    messagingSenderId: '726749633874',
    projectId: 'profit-dc48b',
    authDomain: 'profit-dc48b.firebaseapp.com',
    storageBucket: 'profit-dc48b.firebasestorage.app',
    measurementId: 'G-7SJL0TRJYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL_bEFKjfPnFp0nsIWKiy7cv_jTLE0MRU',
    appId: '1:726749633874:android:a78cee82271fa53222ae8b',
    messagingSenderId: '726749633874',
    projectId: 'profit-dc48b',
    storageBucket: 'profit-dc48b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQF5M0tiO3fBpAiZAnaJwxOJyznStZRhs',
    appId: '1:726749633874:ios:e61e5909a9f08d5122ae8b',
    messagingSenderId: '726749633874',
    projectId: 'profit-dc48b',
    storageBucket: 'profit-dc48b.firebasestorage.app',
    iosBundleId: 'com.fitflow.fitflow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQF5M0tiO3fBpAiZAnaJwxOJyznStZRhs',
    appId: '1:726749633874:ios:86145680688ea58922ae8b',
    messagingSenderId: '726749633874',
    projectId: 'profit-dc48b',
    storageBucket: 'profit-dc48b.firebasestorage.app',
    iosBundleId: 'com.profit.profit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ISCdILC8Hpb6FT9qq4mNS_1nZ3Ei-BE',
    appId: '1:726749633874:web:7bd4045aae54ca5622ae8b',
    messagingSenderId: '726749633874',
    projectId: 'profit-dc48b',
    authDomain: 'profit-dc48b.firebaseapp.com',
    storageBucket: 'profit-dc48b.firebasestorage.app',
    measurementId: 'G-S27FTLYPW9',
  );
}
